- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2:
        instance_type: t2.micro
        image: ami-04902260ca3d33422
        region: us-east-1
        key_name: devops
        vpc_subnet_id: subnet-080cd42e12339aabe
        assign_public_ip: yes
        count: 1
        group: eshop
        wait: true
        aws_access_key: "ASIAQXZQJ2TVG7TYWHGL"
        aws_secret_key: "vyOqzxXnywjssxqpafkdWBiWYCkg3STZH3gvbZyu"
        security_token: "FwoGZXIvYXdzEDoaDMC8wSIJWUPyrK946CK3AaiiHT+RWK5FFWEstTubPFRd+J8mp61wztduBF7fmdgANjJTWKJee9gQhtcSaAYBd0T4XrTGGigNjvwCRzfnDZfTbemwDouXqkuAQXKYSf8cNG0JvXbd3TKlETN6jGhEpv+OtOnNnQurN3oU6U6kASNm5XAZOXgd5zIkNDxvNp1nP4Os9lvVL8tbbEqsO+reOK03y4CKz3GZtdwtYv2v2So5G4odJyiaPRl3QhhDhuQcVNCVvBeR3ijsmZmNBjItpa8HAHG1V42vQAsPUnr0gYGVZA9ZaeG93tEQkOQT/MMBXBqnxTR31aiWt1Ap"
      register: ec2

    - name: Add new instance to host group
        add_host:
          hostname: "{{ item.public_ip }}"
          groupname: launched
        loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
        delegate_to: "{{ item.public_dns_name }}"
        wait_for_connection:
          delay: 30
          timeout: 300
        loop: "{{ ec2.instances }}"

- name: Configure EC2
    hosts: launched
    connection: ssh

    tasks:
      - name: Add Centos Extras
        shell: yum-config-manager --enable extras
        become: yes
      - name: Enable Docker package
        shell: amazon-linux-extras enable docker
        become: yes
      - name: Install Docker and Git
        yum:
          name:
            - docker
            - git
          state: latest
          update_cache: yes
        become: yes
      - service:
          name: docker
          state: started
          enable: yes
      - name: Set rights to Docker
        shell: usermod -a -G docker ec2-user
        become: yes
      - name: Checkout Git repo
        git:
          repo: "https://github.com/vfalada/4IT572_docker.git"
          dest: ./app
      - name: Build Docker
        shell: cd app && docker build -t eshop:latest .
        become: yes
      - name: Run eshop
        shell: docker run -p 80:3000 eshop
        async: 45
        poll: 0
        become: yes
      - wait_for:
          port: 80
